<a href="https://colab.research.google.com/github/lmcanavals/algorithmic_complexity2023/blob/main/0109_ex_sudoku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [15]:
%%file 1.txt
1 2 3 4 5 6 7 8 9
4 5 6 7 8 9 1 2 3
7 8 9 1 2 3 4 5 6
2 3 4 5 6 7 8 9 1
5 6 7 8 9 1 2 3 4
8 9 1 2 3 4 5 6 7
3 4 5 6 7 8 9 1 2
6 7 8 9 1 2 3 4 5
9 1 2 3 4 5 6 7 8

Overwriting 1.txt


In [13]:
board = np.loadtxt("1.txt", dtype=int)
print(board)

[[1 2 3 4 5 6 7 8 9]
 [4 5 9 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 3 4 5 6 7 8 9 1]
 [5 6 7 8 9 1 2 3 4]
 [8 9 1 2 3 4 5 6 7]
 [3 4 5 6 7 8 9 1 2]
 [6 7 8 9 1 2 3 4 5]
 [9 1 2 3 4 5 6 7 8]]


In [11]:
def checkVec(vec):
    n = len(vec)
    count = [0]*n
    for e in vec:
        if count[e - 1] > 0:
            return False
        count[e - 1] += 1
    return True

def checkSudoku(board):
    n = len(board)
    for i in range(n):
        if not (checkVec(board[i]) and checkVec(board[:, i])):
            return False
    m = int(n**0.5)
    for f in range(m):
        for c in range(m):
            if not checkVec(board[f*m:(f+1)*m, c*m:(c+1)*m].reshape((n))):
                return False
    return True


True

In [14]:
checkSudoku(board)

False